grails-app/controllers/com/giftbit/sample/oauth/ConnectWithGiftbitController.groovy
package com.giftbit.sample.oauth

class ConnectWithGiftbitController {

    static navigationScope = 'base'
    
    def configService
    def sessionStorageService

    def index() {

        String state = "optionalStateThatWillBeEchoedBack"

        return [state: state]
    }

    def connect(String state) {

        ConfigBean configBean = configService.createConfigBeanFromConfig()
        SessionInfoStorageBean sessionInfo = sessionStorageService.getSavedInfo(session)

        Map connectionParams = [
                client_id    : sessionInfo.app_clientid,
                response_type: "code",
                scope        : sessionInfo.scope,
                redirect_uri : configBean.redirect_url,
                state        : state,
        ]
        String urlParams = connectionParams.collect { k,v -> return "${k.encodeAsURL()}=${v.encodeAsURL()}" }.join('&')

        String connectRedirectString = configBean.giftbit_web_userlogin_endpoint + "?" + urlParams
        println(connectRedirectString)
        redirect(uri: connectRedirectString )

    }

}

grails-app/controllers/com/giftbit/sample/oauth/GiftbitAppCredentialsController.groovy
package com.giftbit.sample.oauth

class GiftbitAppCredentialsController {

    static navigationScope = 'base'

    def configService;
    def sessionStorageService;

    def index() {
        ConfigBean configBean = configService.createConfigBeanFromConfig();
        SessionInfoStorageBean sessionInfoStorageBean = sessionStorageService.getSavedInfo(session)


        return [sessionInfoStorageBean: sessionInfoStorageBean, configBean:configBean, saved: params.saved]
    }

    def save(String app_clientid, String app_secret, String scope) {
        SessionInfoStorageBean sessionInfoStorageBean = new SessionInfoStorageBean(
                app_clientid: app_clientid,
                app_secret: app_secret,
                scope: scope,
        )

        sessionStorageService.saveNewInfo(session, sessionInfoStorageBean)

        redirect( action: "index", params: [saved:true])
    }
}

grails-app/views/giftbitAppCredentials/index.gsp
<head>
    <title>Credentials Storage</title>
    <meta name="layout" content="main"/>
</head>

<body>

<g:if test="${saved}">
    <div class="saved">Credentials Saved</div>
</g:if>

<div class="maincontent">

    These values are always available in your Giftbit account developer portal

    <div class="form">
        <form action="save">
            <span class="label">client_id:</span>
            <g:textField name="app_clientid" value="${sessionInfoStorageBean?.app_clientid}"/>

            <span class="label">client_secret:</span>
            <g:textField name="app_secret" value="${sessionInfoStorageBean?.app_secret}"/>

            <g:select name="scope" from="${configBean.scopes}" />

            <g:submitButton name="Save"/>
        </form>
    </div>
</div>

<g:if test="${sessionInfoStorageBean?.app_clientid}">
    <ul class="nav">
        <li class="nextnav buttons">
            <g:link controller="connectWithGiftbit">Next: Connect With Giftbit</g:link>
        </li>
    </ul>
</g:if>

</body>