grails-app/controllers/com/giftbit/sample/oauth/GiftbitApiCallsController.groovy
package com.giftbit.sample.oauth

import grails.plugins.rest.client.RestBuilder
import groovy.json.JsonOutput

class GiftbitApiCallsController {

    static navigationScope = 'base'

    def configService
    def sessionStorageService

    def index() {
        ConfigBean configBean = configService.createConfigBeanFromConfig();
        SessionInfoStorageBean sessionInfoStorageBean = sessionStorageService.getSavedInfo(session)

        String endpoint = sessionInfoStorageBean.scope == "PAYMENT" ? configBean.giftbit_api_payment_endpoint : configBean.giftbit_api_gift_endpoint
        String accessToken = sessionInfoStorageBean?.user_token
        String requestBody = null
        String method = "GET"
        String acceptString = "application/json"
        String contentTypeString = "application/json"

        RestBuilder rest = new RestBuilder()
        def jsonResponse = rest.get(endpoint) {
            header('AUTHORIZATION', accessToken)
            accept(acceptString)
            contentType(contentTypeString)
        }

        String jsonOut = JsonOutput.prettyPrint(jsonResponse.json.toString())
        render(view: "index", model: [json: jsonOut, endpoint: endpoint, method:method, body: requestBody, header:'AUTHORIZATION: '+accessToken,accept:acceptString, contentType:contentTypeString, status:jsonResponse.status])
    }

    def getGiftcode(String giftcode) {
        ConfigBean configBean = configService.createConfigBeanFromConfig();
        SessionInfoStorageBean sessionInfoStorageBean = sessionStorageService.getSavedInfo(session)

        String endpoint = configBean.giftbit_api_payment_endpoint+"gift/"+(giftcode?:"")
        String accessToken = sessionInfoStorageBean?.user_token
        String requestBody = null
        String method = "GET"
        String acceptString = "application/json"
        String contentTypeString = "application/json"
        String pageform = "gift_display"

        RestBuilder rest = new RestBuilder()
        def jsonResponse = rest.get(endpoint) {
            header('AUTHORIZATION', accessToken)
            accept(acceptString)
            contentType(contentTypeString)
        }

        String jsonOut = JsonOutput.prettyPrint(jsonResponse.json.toString())
        render(view: "index", model: [pageform:pageform, giftcode:giftcode, json: jsonOut, endpoint: endpoint, method:method, body: requestBody, header:'AUTHORIZATION: '+accessToken,accept:acceptString, contentType:contentTypeString, status:jsonResponse.status])
    }

    def redeemGiftcode(String giftcode, Long amount_to_redeem_in_cents, Long transaction_id) {
        ConfigBean configBean = configService.createConfigBeanFromConfig();
        SessionInfoStorageBean sessionInfoStorageBean = sessionStorageService.getSavedInfo(session)
        transaction_id = transaction_id ?: Calendar.getInstance().getTimeInMillis()
        String endpoint = configBean.giftbit_api_payment_endpoint+"gift/"+(giftcode?:"")+"?amount_in_cents=${amount_to_redeem_in_cents}&transaction_id=${transaction_id}"
        String accessToken = sessionInfoStorageBean?.user_token
        String requestBody = null
        String method = "PUT"
        String acceptString = "application/json"
        String contentTypeString = "application/json"
        String pageform = "gift_redeem"



        RestBuilder rest = new RestBuilder()
        def jsonResponse = rest.put(endpoint) {
            header('AUTHORIZATION', accessToken)
            accept(acceptString)
            contentType(contentTypeString)
        }

        String jsonOut = JsonOutput.prettyPrint(jsonResponse.json.toString())
        render(view: "index", model: [pageform:pageform, transaction_id:transaction_id, amount_to_redeem_in_cents:amount_to_redeem_in_cents, giftcode:giftcode, json: jsonOut, endpoint: endpoint, method:method, body: requestBody, header:'AUTHORIZATION: '+accessToken,accept:acceptString, contentType:contentTypeString, status:jsonResponse.status])
    }


    def showCampaigns() {
        ConfigBean configBean = configService.createConfigBeanFromConfig();
        SessionInfoStorageBean sessionInfoStorageBean = sessionStorageService.getSavedInfo(session)

        String endpoint = configBean.giftbit_api_gift_endpoint+"/campaign"
        String accessToken = sessionInfoStorageBean?.user_token
        String requestBody = null
        String method = "GET"
        String acceptString = "application/json"
        String contentTypeString = "application/json"

        RestBuilder rest = new RestBuilder()
        def jsonResponse = rest.get(endpoint) {
            header('AUTHORIZATION', accessToken)
            accept(acceptString)
            contentType(contentTypeString)
        }

        String jsonOut = JsonOutput.prettyPrint(jsonResponse.json.toString())
        render(view: "index", model: [json: jsonOut, endpoint: endpoint, method:method, body: requestBody, header:'AUTHORIZATION: '+accessToken,accept:acceptString, contentType:contentTypeString, status:jsonResponse.status])
    }

    def showMarketplace() {
        ConfigBean configBean = configService.createConfigBeanFromConfig();
        SessionInfoStorageBean sessionInfoStorageBean = sessionStorageService.getSavedInfo(session)

        String endpoint = configBean.giftbit_api_gift_endpoint+"/marketplace"
        String accessToken = sessionInfoStorageBean?.user_token
        String requestBody = null
        String method = "GET"
        String acceptString = "application/json"
        String contentTypeString = "application/json"

        RestBuilder rest = new RestBuilder()
        def jsonResponse = rest.get(endpoint) {
            header('AUTHORIZATION', accessToken)
            accept(acceptString)
            contentType(contentTypeString)
        }

        String jsonOut = JsonOutput.prettyPrint(jsonResponse.json.toString())
        render(view: "index", model: [json: jsonOut, endpoint: endpoint, method:method, body: requestBody, header:'AUTHORIZATION: '+accessToken,accept:acceptString, contentType:contentTypeString, status:jsonResponse.status])
    }


    def refreshToken() {
        ConfigBean configBean = configService.createConfigBeanFromConfig();
        SessionInfoStorageBean sessionInfoStorageBean = sessionStorageService.getSavedInfo(session)

        String refresh_token = sessionInfoStorageBean?.user_refresh
        String endpoint = configBean.giftbit_api_token_endpoint
        String accessToken = sessionInfoStorageBean?.user_token
        String requestBody = "grant_type=${configBean?.grant_refresh}&client_id=${sessionInfoStorageBean?.app_clientid?:""}&client_secret=${sessionInfoStorageBean?.app_secret?:""}&refresh_token=${refresh_token?.encodeAsURL()?:""}"
        String method = "POST"
        String acceptString = "application/json"
        String contentTypeString = "application/x-www-form-urlencoded"

        RestBuilder rest = new RestBuilder()
        def jsonResponse = rest.post(endpoint) {
            accept(acceptString)
            contentType(contentTypeString)
            body(requestBody)
        }

        accessToken = jsonResponse.json.access_token ?: sessionInfoStorageBean?.user_token
        refresh_token = jsonResponse.json.refresh_token ?: sessionInfoStorageBean?.user_refresh

        sessionInfoStorageBean?.user_refresh = refresh_token
        sessionInfoStorageBean?.user_token = accessToken
        sessionStorageService.saveNewInfo(session, sessionInfoStorageBean)

        String jsonOut = JsonOutput.prettyPrint(jsonResponse.json.toString())
        render(view: "index", model: [json: jsonOut, endpoint: endpoint, method:method, body: requestBody, header:null,accept:acceptString, contentType:contentTypeString, status:jsonResponse.status])
    }

    def error(String error, String error_description) {
        return [error: error, error_description: error_description]
    }
}

grails-app/views/giftbitApiCalls/error.gsp
<head>
    <title>Callback Error</title>
    <meta name="layout" content="main" />
</head>

<body>

    <h2>Error from the server</h2>
    <div class="error">${error}:${error_description}</div>




</body>

grails-app/views/giftbitApiCalls/index.gsp
<head>
    <title>Call to Giftbit</title>
    <meta name="layout" content="main"/>
</head>

<body>
<div class="maincontent">

    <span class="label">Request</span>
    <ul class="apiCall">
        <li>
            <span class="label">endpoint</span>
            <span class="value">${endpoint}</span>
        </li>
        <li>
            <span class="label">method</span>
            <span class="value">${method}</span>
        </li>
        <li>
            <span class="label">header</span>
            <span class="value">${header}</span>
        </li>
        <li>
            <span class="label">accept</span>
            <span class="value">${accept}</span>
        </li>
        <li>
            <span class="label">contentType</span>
            <span class="value">${contentType}</span>
        </li>


        <li>
            <span class="label">body</span>
            <span class="value"><pre>${body}</pre></span>
        </li>

    </ul>

    <hr class="widebreak"/>

    <span class="label">Response</span>
    <ul class="apiCall">
        <li>
            <span class="label">status</span>
            <span class="value">${status}</span>
        </li>
        <li>
            <span class="label">body</span>
            <span class="value">
                <pre>${json}</pre>
            </span>
        </li>
    </ul>

    <g:if test="${pageform == 'gift_display'}" >
        <g:form action="getGiftcode" name="gift_details">
            <hr class="widebreak"/>
            <span class="label">Gift Details</span>
            <ul class="apiCall">
                    <li>
                        <span class="label">giftcode</span>
                        <span class="value"><g:textField name="giftcode" valu="${giftcode}" placeholder="Giftcode"/></span>
                    </li>
            <li>
                <span class="label"> </span>
                <span class="value">
                    <g:submitButton name="Go"/>
                </span>
            </li>
        </g:form>
    </g:if>
    <g:elseif test="${pageform=='gift_redeem'}" >
        <g:form action="redeemGiftcode" name="gift_redeem" >
            <hr class="widebreak"/>
            <span class="label">Gift Redemption</span>
            <ul class="apiCall">
                    <li>
                        <span class="label">Giftcode</span>
                        <span class="value"><g:textField name="giftcode" value="${giftcode}" placeholder="Giftcode"/></span>
                    </li>
                <li>
                    <span class="label">Amount</span>
                    <span class="value"><g:textField type="number" name="amount_to_redeem_in_cents" value="${amount_to_redeem_in_cents}" placeholder="Amount to Redeem in cents"/></span>
                </li>
                 <li>
                     <span class="label">Transaction Id (Leave blank to use current time)</span>
                     <span class="value"><g:textField type="text" name="transaction_id" value="${transaction_id}" placeholder="Unique transaction Id"/></span>
                 </li>
                    <li>
                <span class="label"> </span>
                <span class="value">
                    <g:submitButton name="Go"/>
                </span>
            </li>
        </g:form>
    </g:elseif>

</div>

<ul class="nav">
    <li class="nextnav buttons">
        <g:link controller="giftbitApiCalls" action="index">Credentials Check</g:link>
    </li>
    <li class="nextnav buttons">
<g:link controller="giftbitApiCalls" action="showCampaigns">List Campaigns</g:link>
    </li>
    <li class="nextnav buttons">
    <g:link controller="giftbitApiCalls" action="showMarketplace">List MarketplaceGift</g:link>
    </li>
    <li class="nextnav buttons">
        <g:link controller="giftbitApiCalls" action="refreshToken">Refresh Token</g:link>
    </li>
    <li class="nextnav buttons">
        <g:link controller="giftbitApiCalls" action="getGiftcode">Gift Details</g:link>
    </li>
    <li class="nextnav buttons">
        <g:link controller="giftbitApiCalls" action="redeemGiftcode">Redeem Gift</g:link>
    </li>
</ul>
</body>